# Generated by Django 4.2.3 on 2023-08-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='earliest_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
