# Generated by Django 4.2.3 on 2023-08-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttaxon',
            name='genus',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
