# Generated by Django 4.2.3 on 2023-09-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flora", "0002_alter_taxon_introduced")]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="primary_checklist",
            field=models.BooleanField(default=False),
        )
    ]
