# Generated by Django 4.2.3 on 2023-08-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0002_checklisttaxon_genus'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttaxon',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
