# Generated by Django 4.2.3 on 2023-09-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0003_checklist_primary_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
