# Generated by Django 4.2.3 on 2023-08-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0003_checklisttaxon_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttaxon',
            name='present',
        ),
    ]
