# Generated by Django 4.2.3 on 2023-08-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0005_alter_checklistrecord_canonical_mapped_taxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttaxon',
            name='mapped_taxa',
            field=models.ManyToManyField(blank=True, related_name='taxon_checklist_taxa', to='flora.taxon'),
        ),
    ]
