# Generated by Django 4.2.3 on 2023-08-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0006_alter_checklisttaxon_mapped_taxa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationtype',
            name='observation_type',
            field=models.CharField(choices=[('IR', 'Research grade (iNaturalist)'), ('IN', 'Needs ID (iNaturalist)'), ('IC', 'Casual (iNaturalist)'), ('SG', 'General research (SEINet)'), ('SC', 'Collection (SEINet)'), ('FP', 'Bowers present in flora'), ('FM', 'Bowers missing from flora'), ('UK', 'Unknown')], max_length=2),
        ),
    ]
