# Generated by Django 4.2.3 on 2023-08-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0007_alter_observationtype_observation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttaxon',
            name='observation_types',
            field=models.ManyToManyField(blank=True, related_name='checklist_taxon_observation_types', to='flora.observationtype'),
        ),
        migrations.AddField(
            model_name='checklisttaxon',
            name='on_checklists',
            field=models.ManyToManyField(blank=True, related_name='checklist_taxon_on_checklists', to='flora.checklist'),
        ),
    ]
