# Generated by Django 4.2.5 on 2023-09-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0007_checklistrecordnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='florarecord',
            name='notes',
            field=models.ManyToManyField(blank=True, to='flora.checklistrecordnote'),
        ),
        migrations.AddField(
            model_name='inatrecord',
            name='notes',
            field=models.ManyToManyField(blank=True, to='flora.checklistrecordnote'),
        ),
        migrations.AddField(
            model_name='seinetrecord',
            name='notes',
            field=models.ManyToManyField(blank=True, to='flora.checklistrecordnote'),
        ),
    ]
