# Generated by Django 4.2.5 on 2023-09-10 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0009_alter_checklistrecordnote_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistrecordnote',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
