# Generated by Django 4.2.3 on 2023-08-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0009_remove_checklisttaxon_on_checklists'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxon',
            unique_together={('taxon_name',)},
        ),
    ]
