# Generated by Django 4.2.3 on 2023-08-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0010_alter_taxon_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='endemic',
            field=models.CharField(blank=True, choices=[('n', 'Not endemic'), ('u', 'In the US only in Rincons but also occurs outside of the US'), ('z', 'In {state} only found in {checklist_name} but also occurs outside of {checklist_state}'), ('a', '{checklist_state}'), ('r', '{checklist_name}')], max_length=1, null=True),
        ),
    ]
