# Generated by Django 4.2.3 on 2023-08-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0011_alter_taxon_endemic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='endemic',
            field=models.CharField(blank=True, choices=[('n', 'Not endemic'), ('u', 'In the US only in Rincons but also occurs outside of the US'), ('z', 'In Arizona only found in Rincons but also occurs outside of Arizona'), ('a', 'Only found in Arizona'), ('r', 'Only found in Rincons')], max_length=1, null=True),
        ),
    ]
