# Generated by Django 4.2.3 on 2023-08-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0012_alter_taxon_endemic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='life_cycle',
            field=models.CharField(blank=True, choices=[('a', 'Annual'), ('p', 'Perennial'), ('u', 'Unknown')], max_length=1, null=True),
        ),
    ]
