# Generated by Django 4.2.5 on 2023-09-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0012_alter_seinetrecord_verbatim_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seinetrecord',
            name='type_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
