# Generated by Django 4.2.5 on 2023-09-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0013_seinetrecord_type_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='florarecord',
            name='observation_type',
            field=models.CharField(choices=[('P', 'Present'), ('M', 'Missing'), ('S', 'Suspected')], max_length=1),
        ),
    ]
