# Generated by Django 4.2.5 on 2023-09-17 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0017_checklist_collector_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('p', 'Personal collection'), ('h', 'Submitted to herbarium')], max_length=1)),
                ('inat_record_id', models.IntegerField(blank=True, null=True)),
                ('seinet_record_id', models.IntegerField(blank=True, null=True)),
                ('family', models.CharField(max_length=256)),
                ('preliminary_taxon', models.CharField(max_length=256)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True)),
                ('elevation_ft', models.IntegerField(blank=True, null=True)),
                ('locality', models.TextField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('associated_collectors', models.TextField(blank=True, null=True)),
                ('associated_species', models.TextField(blank=True, null=True)),
                ('specific_taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flora.taxon')),
            ],
        ),
    ]
