# Generated by Django 4.2.5 on 2023-09-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flora", "0018_personalcollectionrecord")]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="checklist_type",
            field=models.CharField(
                choices=[("i", "iNaturalist"), ("s", "SEINet"), ("f", "Flora")],
                max_length=1,
            ),
        )
    ]
