# Generated by Django 4.2.5 on 2023-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0022_personalcollectionrecord_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcollectionrecord',
            name='identification_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
