# Generated by Django 4.2.5 on 2023-09-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0023_personalcollectionrecord_identification_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcollectionrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
