# Generated by Django 4.2.5 on 2023-09-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flora", "0027_remove_taxon_first_observation_date_and_more")]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="first_observation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="last_observation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
