# Generated by Django 4.2.5 on 2023-09-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flora", "0029_remove_taxon_observation_dates_and_more")]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="first_observation_date_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="last_observation_date_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
