# Generated by Django 4.2.5 on 2023-09-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flora", "0030_taxon_first_observation_date_url_and_more")]

    operations = [
        migrations.AlterField(
            model_name="personalcollectionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("p", "Personal collection"),
                    ("h", "Submitted to herbarium"),
                    ("t", "Thrown out"),
                ],
                max_length=1,
            ),
        )
    ]
