# Generated by Django 4.2.5 on 2023-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flora", "0032_taxon_local_population_disjunct_and_more")]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="life_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Annual"),
                    ("p", "Perennial"),
                    ("b", "Biennial"),
                    ("u", "Unknown"),
                ],
                max_length=1,
                null=True,
            ),
        )
    ]
