# Generated by Django 4.2.5 on 2023-09-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0034_taxon_has_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='seinetrecord',
            name='unknown_date',
            field=models.BooleanField(default=False),
        ),
    ]
