# Generated by Django 4.2.5 on 2023-09-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0035_seinetrecord_unknown_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('external_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='CollectorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.TextField()),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flora.collector')),
            ],
            options={
                'unique_together': {('alias',)},
            },
        ),
    ]
