# Generated by Django 4.2.5 on 2023-09-24 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("flora", "0036_collector_collectoralias")]

    operations = [
        migrations.AlterField(
            model_name="collectoralias",
            name="collector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collector_aliases",
                to="flora.collector",
            ),
        )
    ]
