# Generated by Django 4.2.5 on 2023-09-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0041_alter_collector_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='occurrence_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
