# Generated by Django 4.2.5 on 2023-10-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0042_taxon_occurrence_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
