# Generated by Django 4.2.5 on 2023-10-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0043_taxon_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='florarecord',
            name='missing_from_herbarium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inatrecord',
            name='missing_from_herbarium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seinetrecord',
            name='missing_from_herbarium',
            field=models.BooleanField(default=False),
        ),
    ]
