# Generated by Django 4.2.5 on 2023-10-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0044_florarecord_missing_from_herbarium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerbariumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
