name: Tests

on: [push, pull_request]

jobs:
  django-test:
    runs-on: ubuntu-latest
    name: Django tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flora_synthesis/requirements.txt
      - name: Run tests
        run: |
          cd flora_synthesis
          python manage.py migrate
          python manage.py test
